
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 16;
  public static final int POW = 53;
  public static final int LBRACKET = 9;
  public static final int CHAR = 23;
  public static final int LTEQ = 44;
  public static final int POOL = 28;
  public static final int COLONEQ = 41;
  public static final int LPAREN = 4;
  public static final int SEMI = 2;
  public static final int INT = 21;
  public static final int MINUS = 37;
  public static final int CHARACTER = 13;
  public static final int RPAREN = 5;
  public static final int AND = 47;
  public static final int NOT = 11;
  public static final int LCURL = 7;
  public static final int LT = 42;
  public static final int OR = 48;
  public static final int IN = 34;
  public static final int TDEF = 29;
  public static final int QMARK = 54;
  public static final int BOOL = 14;
  public static final int COMMA = 6;
  public static final int FI = 26;
  public static final int DIV = 39;
  public static final int RAT = 20;
  public static final int PLUS = 36;
  public static final int LOOP = 27;
  public static final int MAIN = 51;
  public static final int IF = 25;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 50;
  public static final int RBRACKET = 10;
  public static final int error = 1;
  public static final int MOD = 40;
  public static final int NUMBER = 17;
  public static final int BREAK = 30;
  public static final int FDEF = 31;
  public static final int IMPLY = 49;
  public static final int EQ = 45;
  public static final int TOP = 18;
  public static final int COLONCOLON = 12;
  public static final int RCURL = 8;
  public static final int TIMES = 38;
  public static final int COLON = 3;
  public static final int DICT = 15;
  public static final int ELSE = 33;
  public static final int READ = 52;
  public static final int FLOAT = 22;
  public static final int THEN = 32;
  public static final int STRING = 55;
  public static final int ALIAS = 24;
  public static final int GT = 43;
  public static final int NOTEQ = 46;
  public static final int IDENTIFIER = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "COLON",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "LCURL",
  "RCURL",
  "LBRACKET",
  "RBRACKET",
  "NOT",
  "COLONCOLON",
  "CHARACTER",
  "BOOL",
  "DICT",
  "SEQ",
  "NUMBER",
  "TOP",
  "BOOLEAN",
  "RAT",
  "INT",
  "FLOAT",
  "CHAR",
  "ALIAS",
  "IF",
  "FI",
  "LOOP",
  "POOL",
  "TDEF",
  "BREAK",
  "FDEF",
  "THEN",
  "ELSE",
  "IN",
  "IDENTIFIER",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "COLONEQ",
  "LT",
  "GT",
  "LTEQ",
  "EQ",
  "NOTEQ",
  "AND",
  "OR",
  "IMPLY",
  "RETURN",
  "MAIN",
  "READ",
  "POW",
  "QMARK",
  "STRING"
  };
}

